version: '3.8'

services:
  # PHP 7.4 with Apache
  app:
    build: .
    container_name: simple_pos_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=simple_pos_ci3
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    networks:
      - pos_network

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: simple_pos_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_pos_ci3
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - pos_network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simple_pos_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - pos_network

volumes:
  db_data:
    driver: local

networks:
  pos_network:
    driver: bridge